name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Start Development Container
        run: bash .devcontainer/start-container.sh

      

      - name: Install Dependencies
        run: npm install
      - name: playwright install
        run: npx playwright install

      - name: Install playwright Dependencies
        run: npx playwright install-deps

      - name: Debug File System
        run: ls -al && ls -al tests && ls -al tests/e2e

      - name: Start Laravel Server
        run: php artisan serve --host=0.0.0.0 --port=8000 &

      - run: curl --fail-with-body http://localhost:8000

      - name: Run Playwright Tests
        run: npx playwright test tests/e2e/account.spec.ts



